# P1MeterKit V2 - Base Configuration
# Core functionality shared between all firmware variants
substitutions:
  # Product identification
  device_name: p1meterkit
  friendly_name: P1MeterKit
  software_version: "2.2"
  hardware_version: "V2"
  
  # OTA manifest URL
  manifest_url: "https://smarthomeshop.github.io/p1meterkit/p1meterkit-v2-manifest.json"
  
  # Default values
  default_network: "WiFi"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: "smarthomeshop.p1meterkit"
    version: ${software_version}

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino

# === Core Components ===
logger:
  baud_rate: 115200
  level: WARN

api:

ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_http

http_request:
  useragent: p1meterkit-esphome
  verify_ssl: false
  timeout: 10s

web_server:
  port: 80

# === Firmware Update Component ===
update:
  - platform: http_request
    name: "${friendly_name} Firmware"
    id: firmware_update
    source: ${manifest_url}

# === Status LED ===
status_led:
  pin: GPIO10

# === LED Outputs ===
output:
  - platform: ledc
    id: led_green_out
    pin: GPIO1

light:
  - platform: monochromatic
    id: light_led_green
    name: "${friendly_name} LED Green"
    output: led_green_out

# === Device Controls ===
switch:
  - platform: restart
    id: switch_restart
    name: "${friendly_name} Restart"

button:
  - platform: factory_reset
    name: "${friendly_name} Factory Reset"
    entity_category: config
    disabled_by_default: true

# === I2C Bus ===
i2c:
  scl: GPIO4
  sda: GPIO5
  scan: true
  frequency: 400kHz

# === DSMR P1 Meter ===
uart:
  id: uart_dsmr
  rx_pin:
    number: GPIO3
    inverted: true
  baud_rate: 115200
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 1700

dsmr:
  uart_id: uart_dsmr
  gas_mbus_id: 1
  crc_check: false
  request_pin: GPIO0
  max_telegram_length: 1700

# === Sensors ===
sensor:
  # HDC1080 Temperature & Humidity Sensor
  - platform: hdc1080
    temperature:
      id: sensor_temperature
      name: "${friendly_name} Temperature"
      filters:
        offset: -5.5
    humidity:
      id: sensor_humidity
      name: "${friendly_name} Humidity"
      filters:
        offset: 12
    update_interval: 60s

  # === DSMR Readings ===
  - platform: dsmr
    energy_delivered_tariff1:
      id: dsmr_electricity_delivered_1
      name: "Energy Consumed Tariff 1"
      state_class: total_increasing
    energy_returned_tariff1:
      id: dsmr_electricity_returned_1
      name: "Energy Produced Tariff 1"
      state_class: total_increasing
    energy_delivered_tariff2:
      id: dsmr_electricity_delivered_2
      name: "Energy Consumed Tariff 2"
      state_class: total_increasing
    energy_returned_tariff2:
      id: dsmr_electricity_returned_2
      name: "Energy Produced Tariff 2"
      state_class: total_increasing
    power_delivered:
      id: dsmr_electricity_currently_delivered
      name: "Power Consumed"
      accuracy_decimals: 3
    power_returned:
      id: dsmr_electricity_currently_returned
      name: "Power Produced"
      accuracy_decimals: 3
    voltage_l1:
      id: dsmr_phase_voltage_l1
      name: "Voltage Phase 1"
    voltage_l2:
      id: dsmr_phase_voltage_l2
      name: "Voltage Phase 2"
    voltage_l3:
      id: dsmr_phase_voltage_l3
      name: "Voltage Phase 3"
    current_l1:
      id: dsmr_phase_power_current_l1
      name: "Current Phase 1"
    current_l2:
      id: dsmr_phase_power_current_l2
      name: "Current Phase 2"
    current_l3:
      id: dsmr_phase_power_current_l3
      name: "Current Phase 3"
    power_delivered_l1:
      id: dsmr_phase_currently_delivered_l1
      name: "Power Consumed Phase 1"
      accuracy_decimals: 3
    power_delivered_l2:
      id: dsmr_phase_currently_delivered_l2
      name: "Power Consumed Phase 2"
      accuracy_decimals: 3
    power_delivered_l3:
      id: dsmr_phase_currently_delivered_l3
      name: "Power Consumed Phase 3"
      accuracy_decimals: 3
    power_returned_l1:
      id: dsmr_phase_currently_returned_l1
      name: "Power Produced Phase 1"
      accuracy_decimals: 3
    power_returned_l2:
      id: dsmr_phase_currently_returned_l2
      name: "Power Produced Phase 2"
      accuracy_decimals: 3
    power_returned_l3:
      id: dsmr_phase_currently_returned_l3
      name: "Power Produced Phase 3"
      accuracy_decimals: 3
    gas_delivered:
      id: dsmr_extra_device_delivered
      name: "Gas Consumed"
      state_class: total_increasing

# === Text Sensors ===
text_sensor:
  - platform: dsmr
    identification:
      name: "${friendly_name} DSMR Identification"
    p1_version:
      name: "${friendly_name} DSMR Version"
    timestamp:
      id: dsmr_timestamp
      internal: true

  - platform: version
    id: text_sensor_version
    name: "${friendly_name} ESPHome Version"

  - platform: template
    id: text_sensor_p1meterkit_version
    name: "${friendly_name} Software Version"
    update_interval: 5h
    lambda: |-
      return {"${software_version}"};

  - platform: template
    name: "${friendly_name} Hardware Version"
    lambda: 'return {"${hardware_version}"};'
    update_interval: 5h
