substitutions:
  device_name: p1meterkit
  friendly_name: P1MeterKit
  p1meterkit_software_version: "1.0"
  p1meterkit_hardware_version: "V2"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: "smarthomeshop.p1meterkit"
    version: ${p1meterkit_software_version}

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino

logger:
  baud_rate: 115200  
  level: WARN
  #hardware_uart: UART0

api:
ota:
  - platform: esphome

dashboard_import:
  package_import_url: github://smarthomeshop/p1meterkit/p1meterkit-v2/p1meterkit.yaml@main

wifi:
  # ssid: !secret wifi_ssid
  # password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: ${device_name}

captive_portal:

esp32_improv:
  authorizer: none

improv_serial:

web_server:
  port: 80

# Status LED (rood)
status_led:
  pin: GPIO10

# Alleen de groene LED als light in HA
output:
  - platform: ledc
    id: led_green_out
    pin: GPIO1

light:
  - platform: monochromatic
    id: light_led_green
    name: "${friendly_name} LED Green"
    output: led_green_out


switch:
  - platform: restart
    id: switch_restart
    name: "${friendly_name} Restart"

# I2C (HDC1080)
i2c:
  scl: GPIO4
  sda: GPIO5
  scan: true
  frequency: 400kHz


uart:
  id: uart_dsmr
  rx_pin:
    number: GPIO3
    inverted: true
  baud_rate: 115200
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 1700
  # debug:
  #   direction: RX
  #   dummy_receiver: true


dsmr:
  uart_id: uart_dsmr
  gas_mbus_id: 1
  crc_check: false
  request_pin: GPIO0
  max_telegram_length: 1700



sensor:
  - platform: wifi_signal
    id: sensor_wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 300s

  - platform: dsmr
    energy_delivered_tariff1:
      id: dsmr_electricity_delivered_1
      name: "Energy Consumed Tariff 1"
      state_class: total_increasing
    energy_returned_tariff1:
      id: dsmr_electricity_returned_1
      name: "Energy Produced Tariff 1"
      state_class: total_increasing
    energy_delivered_tariff2:
      id: dsmr_electricity_delivered_2
      name: "Energy Consumed Tariff 2"
      state_class: total_increasing
    energy_returned_tariff2:
      id: dsmr_electricity_returned_2
      name: "Energy Produced Tariff 2"
      state_class: total_increasing
    power_delivered:
      id: dsmr_electricity_currently_delivered
      name: "Power Consumed"
      accuracy_decimals: 3
    power_returned:
      id: dsmr_electricity_currently_returned
      name: "Power Produced"
      accuracy_decimals: 3
    voltage_l1:
      id: dsmr_phase_voltage_l1
      name: "Voltage Phase 1"
    voltage_l2:
      id: dsmr_phase_voltage_l2
      name: "Voltage Phase 2"
    voltage_l3:
      id: dsmr_phase_voltage_l3
      name: "Voltage Phase 3"
    current_l1:
      id: dsmr_phase_power_current_l1
      name: "Current Phase 1"
    current_l2:
      id: dsmr_phase_power_current_l2
      name: "Current Phase 2"
    current_l3:
      id: dsmr_phase_power_current_l3
      name: "Current Phase 3"
    power_delivered_l1:
      id: dsmr_phase_currently_delivered_l1
      name: "Power Consumed Phase 1"
      accuracy_decimals: 3
    power_delivered_l2:
      id: dsmr_phase_currently_delivered_l2
      name: "Power Consumed Phase 2"
      accuracy_decimals: 3
    power_delivered_l3:
      id: dsmr_phase_currently_delivered_l3
      name: "Power Consumed Phase 3"
      accuracy_decimals: 3
    power_returned_l1:
      id: dsmr_phase_currently_returned_l1
      name: "Power Produced Phase 1"
      accuracy_decimals: 3
    power_returned_l2:
      id: dsmr_phase_currently_returned_l2
      name: "Power Produced Phase 2"
      accuracy_decimals: 3
    power_returned_l3:
      id: dsmr_phase_currently_returned_l3
      name: "Power Produced Phase 3"
      accuracy_decimals: 3
    gas_delivered:
      id: dsmr_extra_device_delivered
      name: "Gas Consumed"
      state_class: total_increasing

  - platform: hdc1080
    temperature:
      id: sensor_temperature
      name: "${friendly_name} Temperature"
      filters: { offset: -5.5 }
    humidity:
      id: sensor_humidity
      name: "${friendly_name} Humidity"
      filters: { offset: 12 }
    update_interval: 60s

text_sensor:
  - platform: dsmr
    identification:
      name: "${friendly_name} DSMR Identification"
    p1_version:
      name: "${friendly_name} DSMR Version"
    timestamp:
      id: dsmr_timestamp
      internal: true

  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP address"
      icon: "mdi:network-outline"
    ssid:
      name: "${friendly_name} Connected SSID"
    bssid:
      name: "${friendly_name} Connected BSSID"

  - platform: version
    id: text_sensor_version
    name: "${friendly_name} ESPHome Version"

  - platform: template
    id: text_sensor_p1meterkit_version
    name: "${friendly_name} Software Version"
    update_interval: 5h
    lambda: |-
      return {"${p1meterkit_software_version}"};

  - platform: template
    id: text_sensor_p1meterkit_hardware_version
    name: "${friendly_name} Hardware Version"
    update_interval: 5h
    lambda: |-
      return {"${p1meterkit_hardware_version}"};
