# P1MeterKit V2 WiFi Configuration
# Main entry point for WiFi firmware
# ESP32-C3 based with Improv support

substitutions:
  default_network: "WiFi"

packages:
  base: !include base.yaml
  wifi: !include wifi.yaml

dashboard_import:
  package_import_url: github://smarthomeshop/p1meterkit/p1meterkit-v2/p1meterkit.yaml@main
