# P1MeterKit V2 - WiFi Network Configuration

wifi:
  # No WiFi credentials - device starts in AP mode for initial setup
  # Users can configure WiFi via:
  # - Captive Portal (connect to hotspot)
  # - Improv BLE (via Bluetooth)
  # - Improv Serial (via USB)
  # - ESPHome dashboard (after adoption)
  
  ap:
    ssid: ${device_name}
    password: ${device_name}

captive_portal:

# Improv BLE (for WiFi provisioning via Bluetooth)
esp32_improv:
  authorizer: none

# Improv Serial (for WiFi provisioning via USB)
improv_serial:

sensor:
  # WiFi signal strength
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 300s
    id: sensor_wifi_signal

text_sensor:
  # WiFi info
  - platform: wifi_info
    ip_address:
      id: wifi_ip_address
      name: "${friendly_name} IP Address"
      icon: "mdi:network-outline"
    ssid:
      id: wifi_ssid
      name: "${friendly_name} Connected SSID"
    bssid:
      name: "${friendly_name} Connected BSSID"
    mac_address:
      id: wifi_mac_address
      name: "${friendly_name} MAC Address"
      entity_category: diagnostic
