# P1MeterKit V1 WiFi Configuration
# Main entry point for WiFi firmware
# ESP8266 based

substitutions:
  default_network: "WiFi"

packages:
  base: !include base.yaml
  wifi: !include wifi.yaml

dashboard_import:
  package_import_url: github://smarthomeshop/p1meterkit/p1meterkit-v1/p1meterkit.yaml@main
