name: Build and Publish P1MeterKit firmware

on:
  push:
    branches:
      - main
    paths:
      - 'p1meterkit-v2/**'
  pull_request:
    paths:
      - 'p1meterkit-v2/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build P1MeterKit firmware
    runs-on: ubuntu-latest
    outputs:
      firmware_name: ${{ steps.esphome-build.outputs.name }}
      project_version: ${{ steps.prepare.outputs.project_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare version metadata
        id: prepare
        shell: bash
        run: |
          set -euo pipefail

          YAML_FILE="p1meterkit-v2/p1meterkit.yaml"

          python3 <<'PY'
          import os
          import re
          from pathlib import Path

          path = Path("p1meterkit-v2/p1meterkit.yaml")
          text = path.read_text()
          match = re.search(r'p1meterkit_software_version:\s*"([^"]+)"', text)
          if not match:
              raise SystemExit("Kon huidige versie niet vinden")
          current_version = match.group(1)

          version = current_version
          version_changed = False

          ref_type = os.getenv("GITHUB_REF_TYPE", "")
          ref_name = os.getenv("GITHUB_REF_NAME", "")
          event_name = os.getenv("GITHUB_EVENT_NAME", "")
          sha = os.getenv("GITHUB_SHA", "")[:7]

          if ref_type == "tag" and re.fullmatch(r"v\d+(?:\.\d+)*", ref_name or ""):
              version = (ref_name or "")[1:]
          elif event_name == "push" and os.getenv("GITHUB_REF") == "refs/heads/main":
              parts = current_version.split('.')
              try:
                  numbers = [int(part) for part in parts]
              except ValueError:
                  numbers = None
              if numbers:
                  numbers[-1] += 1
                  version = '.'.join(str(n) for n in numbers)
                  version_changed = True
          else:
              version = f"dev-{sha}"

          pattern_version = re.compile(r'(p1meterkit_software_version:\s*)"[^"]+"')
          pattern_project = re.compile(r'(project:\s*\n\s*name:\s*"smarthomeshop\.p1meterkit"\s*\n\s*version:\s*)"[^"]+"')
          updated = pattern_version.sub(rf"\1\"{version}\"", text)
          updated = pattern_project.sub(rf"\1\"{version}\"", updated)
          path.write_text(updated)

          with open(os.environ["GITHUB_OUTPUT"], "a", encoding="utf-8") as fh:
              fh.write(f"project_version={version}\n")
              fh.write(f"version_changed={'true' if version_changed else 'false'}\n")
          PY

      - name: Commit version bump
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.prepare.outputs.version_changed == 'true'
        shell: bash
        run: |
          set -euo pipefail
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add p1meterkit-v2/p1meterkit.yaml
          git commit -m "chore: bump firmware version to ${{ steps.prepare.outputs.project_version }}" || exit 0
          git push || echo "Geen wijzigingen om te pushen"

      - name: Dummy secrets aanmaken
        shell: bash
        run: |
          set -euo pipefail
          printf 'wifi_ssid: "DUMMY"\nwifi_password: "DUMMYPASS"\n' > p1meterkit-v2/secrets.yaml

      - name: ESPHome build uitvoeren
        id: esphome-build
        uses: esphome/build-action@v6
        with:
          yaml-file: p1meterkit-v2/p1meterkit.yaml

      - name: Build artefact verzamelen
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p output/p1meterkit-v2
          mv "${{ steps.esphome-build.outputs.name }}" output/p1meterkit-v2/
          rm -f p1meterkit-v2/secrets.yaml

      - name: Artefact uploaden
        uses: actions/upload-artifact@v4
        with:
          name: p1meterkit-v2-${{ steps.prepare.outputs.project_version }}
          path: output

  publish:
    name: Publiceer naar GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: p1meterkit-v2-${{ needs.build.outputs.project_version }}
          path: output

      - name: Manifest voorbereiden
        shell: bash
        run: |
          set -euo pipefail
          VERSION="${{ needs.build.outputs.project_version }}"
          FIRMWARE_DIR="$PWD/output/p1meterkit-v2/${{ needs.build.outputs.firmware_name }}"
          MANIFEST="$FIRMWARE_DIR/manifest.json"

          if [[ -f "$MANIFEST" ]]; then
            PREFIX="p1meterkit-v2/${{ needs.build.outputs.firmware_name }}/"
            jq \
              --arg version "$VERSION" \
              --arg prefix "$PREFIX" \
              '(.name = "P1MeterKit")
               | (.version = $version)
               | if .builds then .builds |= map(if .ota then .ota.path = $prefix + .ota.path else . end) else . end
               | if .builds then .builds |= map(if .parts then .parts |= map(.path = $prefix + .path) else . end) else . end' \
              "$MANIFEST" > "$MANIFEST.tmp"
            mv "$MANIFEST.tmp" "$MANIFEST"
            cp "$MANIFEST" "$PWD/output/p1meterkit-v2/manifest.json"
          fi

      - name: Deploy naar gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: output
          clean: false
